### PR TITLE
draft of Ch 07

### PR DESCRIPTION
**Pull request by PaulSoderlind**
This is a crude translation of the matlab code for ch 7

Some issues:

1. I don't have the data file ch7_data_crime.txt yet
2. There are some bugs in the matlab code
3. So far, I've kept the (sometimes cumbersome) syntax structure of the matlab code. There is clearly a trade-off between making the code similar to ML/python and to make it elegant.
4. There is a thing or two in the draft that I want/need to change (the robust fitted values are probably wrong...). The draft is just for you to be able to give preliminary feedback on the general style.

### CODE REVIEW

**Comment by mcreel** [comment]
Hi Paul,

This draft clearly follows the original code pretty closely. My opinion is that there's no reason not to take advantage of the features that Julia offers, as long as the correspondence with the original code, and the text of the book, is clear enough to follow. For example, unicode characters, broadcasting.... Also, the original code is inconsistent in the degree to which it is commented. I think we can try to add basic explanatory comments for the main steps, or for anything that students may not be able to follow with ease. 

In my code for Ch8, I added some functionality for the part that explores the effect of the prior and the data, adding the posterior variance, for example, and adding the possibility to sample a number of points. That's an example of how, in my opinion, the original code might be improved. It's still close enough to see that it's doing the same as the Python/Matlab, but it's a bit nicer.

I'm starting to think that we should definitely wrap the code inside functions, to avoid scope problems, and just because good Julia code should be that way.

So, the first stab should try to stay fairly close to the book, I think. Once that's done, I'll ask for feedback from the author. We can always open a more julian branch in the archive, if there are significant gains to be made to doing that.

So, please just proceed as you think best!  

BTW, should I contact Stanley about that broken link, or have you already done that?

**Comment by PaulSoderlind** [comment]
>don't wrap code in functions
OK, I'll minimize it, with one exception: I'll keep the function for the Lasso thing. (It's just very clumsy to put in a loop.)

**Comment by PaulSoderlind** [comment]
I have just uploaded a new draft. The code is a bit more streamlined (fewer clumsy loops). Still no "crimes" data set.

**Comment by PaulSoderlind** [comment]
The data set is now online. I'll change the file and upload again.

**Comment by PaulSoderlind** [comment]
I have added the empirical example. Reasonably, the data should be de-meaned before the LASSO (as there is no constant in `X`) so I did that although that does not show up in the ML code. 

From my perspective, this is ready to be merged.

**Pull request merged**
